# Generated by Django 2.0.5 on 2018-09-12 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('ambient_humidity_min', models.PositiveIntegerField(verbose_name='Ambient Humidity Min')),
                ('ambient_humidity_max', models.PositiveIntegerField(verbose_name='Ambient Humidity Max')),
                ('ambient_temperature_min', models.PositiveIntegerField(verbose_name='Ambient Temperature Min')),
                ('ambient_temperature_max', models.PositiveIntegerField(verbose_name='Ambient Temperature Max')),
                ('sun_time_min', models.PositiveIntegerField(verbose_name='Sun Time Min')),
                ('sun_time_max', models.PositiveIntegerField(verbose_name='Sun Time Max')),
                ('ground_humidity_min', models.PositiveIntegerField(verbose_name='Ground Humidity Min')),
                ('ground_humidity_max', models.PositiveIntegerField(verbose_name='Ground Humidity Max')),
                ('size', models.PositiveIntegerField(verbose_name='Size mts')),
                ('start_time_reading', models.TimeField(verbose_name='Start Time Reading')),
                ('end_time_reading', models.TimeField(verbose_name='End Time Reading')),
                ('sensing_time', models.PositiveIntegerField(verbose_name='Sensing Time')),
                ('opening_time', models.PositiveIntegerField(verbose_name='Opening Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seeding',
                'verbose_name_plural': 'Seedings',
                'db_table': 'seeding',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('pin', models.PositiveIntegerField(verbose_name='Pin')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('type_sensor', models.CharField(choices=[('solenoide_valve', 'Solenoide Valve'), ('light', 'Light Sensor'), ('ambient_humidity', 'Ambient Humidity'), ('ambient_temperature', 'Ambient Temperature'), ('ground_humidity', 'Ground Humidity')], max_length=25, verbose_name='Type Sensor')),
                ('seeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenmatic.Seeding', verbose_name='Seeding')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'sensor',
            },
        ),
    ]
