# Generated by Django 2.0.5 on 2018-10-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenmatic', '0002_sensorreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='pin',
            field=models.PositiveIntegerField(choices=[(4, 'GPIO 4 (Physical 7)'), (5, 'GPIO 5 (Physical 29)'), (6, 'GPIO 6 (Physical 31)'), (12, 'GPIO 12 (Physical 32)'), (13, 'GPIO 13 (Physical 33)'), (16, 'GPIO 16 (Physical 36)'), (17, 'GPIO 17 (Physical 11)'), (18, 'GPIO 18 (Physical 12)'), (19, 'GPIO 19 (Physical 35)'), (20, 'GPIO 20 (Physical 38)'), (21, 'GPIO 21 (Physical 40)'), (22, 'GPIO 22 (Physical 15)'), (23, 'GPIO 23 (Physical 16)'), (24, 'GPIO 24 (Physical 18)'), (25, 'GPIO 25 (Physical 22)'), (26, 'GPIO 26 (Physical 37)'), (27, 'GPIO 27 (Physical 13)')], verbose_name='Pin'),
        ),
    ]
