# Generated by Django 2.0.5 on 2018-10-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenmatic', '0003_auto_20181010_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeding',
            name='ground_humidity_max',
        ),
        migrations.RemoveField(
            model_name='seeding',
            name='ground_humidity_min',
        ),
    ]
